### ISSUE TITLE
Changed meaning of .+= in Julia 0.5

### ISSUE THREAD

**Issue by stevengj** [mkriele/ValueOrientedRiskManagementInsurance.jl#1]
Your code uses `x .+= y`, so you should know that in Julia 0.5 this has changed meaning to be equivalent to `broadcast!(identity, x, x .+ y)`, so that it mutates the `x` array (see JuliaLang/julia#17510 … in Julia 0.6 the whole operation will occur in-place without temporaries).  So `.+` should only be used if the left-hand side is a mutable array, and you don't mind mutating it.

At first glance, this looks like it is okay for you, because you use it in `pl.profit .+= plbu.profit` and similar cases where it looks like you want to work in-place anyway?  But if it were a problem you could always change it to `+=`.

**Comment by mkriele** [comment]
Many thanks for the heads up! I also don't think it is an issue for me but I will look out for it once I switch to 0.5

**Comment by tkelman** [comment]
Looks like you do have an ambiguity failure in your tests now http://pkg.julialang.org/logs/ValueOrientedRiskManagementInsurance_0.5.log

**Comment by stevengj** [comment]
Similarly for `.*=`.  In particular, looking at code like `β[:prem] .*= product.prem_norm`, I'm wondering if you mean `*=`, depending on what `β[:prem]` is?

After JuliaLang/julia#17546 is merged, this will turn into `broadcast!(identity, view(β, :prem), β[:prem] .* product.prem_norm)`, and probably `view(β, :prem)` will throw a `MethodError`. So, probably you will need to change this to `*=` anyway.

**Comment by mkriele** [comment]
Any such errors have been corrected in the current code
