### ISSUE TITLE
update to julia v1.6

### ISSUE THREAD

**Issue by reumle** [mkriele/ValueOrientedRiskManagementInsurance.jl#4]
Hi , I have updated this package to julia v1.6. I will try to do a pull request shortly.
more info in the commit message...
Regards. Emmanuel.

**Comment by mkriele** [comment]
Many thanks, I am looking forward to it.  It will probably take a bit of time to look at your pull request as I am still on a very old Julia version.  By the way, the sections on the Swiss Solvency Test in the book are very much outdated.

**Comment by reumle** [comment]
Hi, my attempt at a pull request failed,   I will try again in a few days.
In the mean time, the fork (with the update commit, only a few statements) is at https://github.com/reumle/ValueOrientedRiskManagementInsurance.jl 
And also thanks a lot for your package! there is a lot to digest and reflect upon!
Cheers! Emmanuel.

**Comment by mkriele** [comment]
Thanks!  I updated the code using your pull request and there is now a new registered version. Best, Marcus
